'use client'

import { useState } from "react"
import { FiMenu } from 'react-icons/fi'
import { AiOutlineClose } from 'react-icons/ai'
import { BsServer } from "react-icons/bs"
import { motion } from 'framer-motion'

const code = {
  "authorization": {
    "amount": "123.04",
    "currency": "PLN"
  }
}

const ApiPage = () => {
  const [isOpenNavMobile, setIsOpenNavMobile] = useState(false);

  return (
    <motion.div
      className="relative flex flex-col lg:flex-row w-full"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ ease: 'linear', duration: 1 }}
    >
      <div className="hidden lg:block basis-[256px] bg-[#e8e9ed] py-20 px-12">
        <h3 className="text-xl text-theme-primary font-semibold">
          AUTORYZACJA
        </h3>
        <div className="border-t-2 border-[#d8d8dc] text-theme-text w-[68px] pt-8 mt-8 space-y-6">
          <button className="block">Terminale</button>
          <button className="block">Transakcje</button>
        </div>
      </div>
      <div className="block lg:hidden text-right px-4 sm:px-10 py-4">
        <div
          className={`${isOpenNavMobile ? 'translate-x-0' : '-translate-x-[100%]'
            } block lg:hidden fixed inset-y-0 left-0 w-full max-w-[256px] bg-[#e8e9ed] border-r-[1px] border-gray-300 py-20 px-8 text-left shadow-lg z-[998] transition-all duration-200 ease-out`}
        >
          <h3 className="text-xl text-theme-primary font-semibold">AUTORYZACJA</h3>
          <div className="border-t-2 border-[#d8d8dc] text-theme-text w-[68px] pt-8 mt-8 space-y-6">
            <button className="block">Terminale</button>
            <button className="block">Transakcje</button>
          </div>
        </div>
        <button onClick={() => setIsOpenNavMobile((display) => !display)}>
          {isOpenNavMobile ? <AiOutlineClose fontSize={24} /> : <FiMenu fontSize={24} />}
        </button>
      </div>
      <div className="py-10 lg:py-20 px-4 sm:px-10 flex-auto space-y-8">
        <div className="flex gap-2 sm:gap-10">
          <div className="text-[#d4d5d9]">
            <BsServer className="text-4xl sm:text-[64px]" />
          </div>
          <div className="space-y-2">
            <h1 className="text-theme-primary underline underline-offset-4 font-bold text-3xl">
              Utwórz transakcję
            </h1>
            <p className="text-theme-text max-w-[640px]">
              Pozwala na utworzenie transakcji (przesyłając parametry transakcji
              do ZEN). Ważne! Dla niektórych metod płatności zostanie zwrócony
              returnUrl. Aby kontynuować transakcję, klient musi zostać
              przekierowany pod ten adres URL.
            </p>
          </div>
        </div>
        <div className="text-2xl flex gap-4">
          <h2 className="text-theme-primary font-semibold text-xl">
            AUTHORIZATIONS
          </h2>
          <h3 className="text-base text-[#0000ff] place-self-center">
            ApiKey
          </h3>
        </div>
        <div className="flex flex-col gap-6">
          <div className="border-b-2 border-[#d8d8dc]">
            <h2 className="text-theme-primary font-semibold text-xl">
              HEADER PARAMETERS
            </h2>
          </div>
          <div className="flex gap-10">
            <p className="text-theme-text w-[100px]">
              request-id
            </p>
            <div className="flex flex-col gap-4 w-full border-b-2 border-[#d8d8dc] pb-4">
              <div className="flex gap-4">
                <p className="text-theme-text">string</p>
                <p className="text-[#0000ff] bg-[#d4d5d9] px-2 mr-2">[ 38 . . 1024 . ] characters</p>
                <p className="text-[#008000]">^[a-zA-Z0-978_|\</p>
              </div>
              <div className="flex flex-col">
                <p className="text-theme-text">Example: <a className="bg-[#d4d5d9]">un04oqdn=FQVr0r109/e90VDRE2BXVEWOLV</a></p>
                <p className="text-theme-text">A unique identifier generated by requesting client</p>
              </div>
            </div>
          </div>
        </div>
        <div className="text-2xl flex gap-4 border-b-2 border-[#d8d8dc]">
          <h2 className="text-theme-primary font-semibold text-xl">
            REQUEST BODY SCHEMA
          </h2>
          <h3 className="text-base text-theme-text place-self-center">
            application/json
          </h3>
        </div>
      </div>
      <div className="relative basis-[376px] bg-[#333] p-4 lg:px-6 lg:pt-20 mb-10 lg:mb-0">
        <div className="bg-[#141213] w-full h-full text-white p-4 flex flex-col">
          <span>Content type</span>
          <span>application/json</span>
          <br />
          <pre>
            {JSON.stringify(code, null, 2)}
          </pre>
        </div>
      </div>
    </motion.div>
  );
};

export default ApiPage;
